### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zhenql** [flaviovdf/prme#2]
when run 
python main.py data_file num_latent_factors model.h5
return: 
  File "main.py", line 4, in <module>
    from prme import dataio
  File "/home/code/poi/prme/prme/__init__.py", line 8, in <module>
    from prme import sgd
ImportError: cannot import name sgd

*
in the dir /home/code/poi/prme/prme
i can run "from prme imort sgd"
but in the dir /home/code/poi/prme/
>>> import prme
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "prme/__init__.py", line 8, in <module>
    from prme import sgd
ImportError: cannot import name sgd

how to solve the problem?
thanks

**Comment by ethanywang** [comment]
The problem can be solved by changing
`from prme import sgd`
to 
`from prme.prme import sgd`

**Comment by ethanywang** [comment]
Moreover, if using python3, the line of 
`import dataio`
needs to be changed to
`from . import dataio`

**Comment by zhenql** [comment]
I'm sorry that I reply you so late and I have solved the problem.
Just because I forget to "make all".
Thank you.
